name: Deploy to GKE

on:
  workflow_dispatch:
    # Enable manual run
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: convocatoria-ascendere
  GKE_ZONE: us-central1 
  DEPLOYMENT_NAME: micro-resources-deployment

jobs:

  push_to_registry:
    name: Push Docker image to Dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: '${{ secrets.DOCKER_USERNAME }}/micro_resources'

  setup-and-deploy:
    name: Setup and Deploy
    needs: push_to_registry
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    - name: Get GKE Credentials
      run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
        
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        # kustomize edit set image ${{ secrets.DOCKER_USERNAME }}/micro_resources
        kustomize build . | kubectl apply -f -
        kubectl patch deployment $DEPLOYMENT_NAME -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide
